In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = np.loadtxt( 'train_challenges.dat' )

In [4]:
data


array([[1., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 1., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.]])

In [5]:
Y=np.loadtxt( 'train_responses.dat' )

In [6]:
Y

array([1852.119682, 2103.222591, 2121.447663, ..., 2026.056949,
       2100.444096, 1988.291136])

In [7]:
Y.size

1600

In [8]:
num_rows, num_cols = data.shape

In [9]:
print(num_rows) 

1600


In [10]:
print(num_cols) 

2048


In [11]:
m=1600
n=2048
X=data

y=Y


# Load the dataset (X: features, y: target variable)


# Normalize the feature values
X_normalized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# Add a column of ones for the bias term
X_normalized = np.hstack((np.ones((X_normalized.shape[0], 1)), X_normalized))

# Initialize model parameters
num_features = X_normalized.shape[1]
theta = np.zeros(num_features)
alpha = 0.01
num_iterations = 1000

# Define the cost function (mean squared error)
def cost_function(X, y, theta):
    m = len(y)
    predictions = np.dot(X, theta)
    error = predictions - y
    cost = np.sum(error ** 2) / (2 * m)
    return cost

# Perform gradient descent
def gradient_descent(X, y, theta, alpha, num_iterations):
    m = len(y)
    cost_history = []
    for _ in range(num_iterations):
        predictions = np.dot(X, theta)
        error = predictions - y
        gradient = np.dot(X.T, error) / m
        theta -= alpha * gradient
        cost = cost_function(X, y, theta)
        cost_history.append(cost)
    return theta, cost_history
optimized_theta, cost_history = gradient_descent(X_normalized, y, theta, alpha, num_iterations)

In [12]:
theta

array([ 2.02798974e+03, -1.11004006e+00,  5.46719165e-01, ...,
        3.47949487e+00,  1.23617398e+00,  6.82854270e-01])

In [13]:
optimized_theta, cost_history = gradient_descent(X_normalized, y, theta, alpha, num_iterations)

In [14]:
optimized_theta

array([ 2.02807729e+03, -1.29056788e+00,  5.34130063e-01, ...,
        3.40167545e+00,  1.08864721e+00,  6.39721824e-01])

In [15]:
cost_history

[11.287018775253568,
 11.264998889916463,
 11.24303995510755,
 11.221141730978971,
 11.19930397919543,
 11.177526462922716,
 11.155808946805013,
 11.134151196953725,
 11.112552980928864,
 11.091014067725569,
 11.06953422775555,
 11.048113232835936,
 11.026750856171047,
 11.00544687233948,
 10.984201057280565,
 10.963013188275795,
 10.941883043940978,
 10.920810404207753,
 10.899795050311782,
 10.878836764779706,
 10.857935331415653,
 10.837090535287638,
 10.816302162716013,
 10.795570001260137,
 10.774893839704944,
 10.754273468052295,
 10.733708677505017,
 10.713199260456149,
 10.692745010478934,
 10.672345722315477,
 10.652001191860972,
 10.631711216158775,
 10.611475593384403,
 10.591294122838704,
 10.571166604934326,
 10.551092841185158,
 10.531072634199372,
 10.511105787665022,
 10.491192106342154,
 10.471331396053777,
 10.451523463673944,
 10.431768117118532,
 10.412065165336687,
 10.392414418303288,
 10.372815687004696,
 10.353268783432757,
 10.33377352057772,
 10.31432971241596

In [16]:
for i in range(0, len(optimized_theta)):    
    print(optimized_theta[i]),    

2028.077292645158
-1.2905678806161456
0.5341300631341075
-1.2146238493724315
0.0530982816002523
3.8972597433413445
-1.1199207843266978
1.099733798026827
-0.021642233051346944
2.6820532706822062
-0.6595987413293251
-0.8064612369818288
1.1762785108863942
-0.13153151401361998
2.1063891380752415
-0.876812436762476
4.7747803478417445
1.7978312307701687
-0.4653976737428982
2.0430573219184445
1.440484462444448
0.1362650908674138
-0.37438203206400705
-0.24124772128087468
0.6591090362889837
-1.8567672841531928
0.16191887647486408
3.517819620367487
0.23136561833195896
-0.2155307630642055
1.3141240301922823
0.144606029767074
3.113644830204942
-0.723544055581531
-0.28606299178481154
-2.069276851423114
-0.24679399381528785
2.5787931402647803
-0.39379757673158294
0.5884799222518046
-0.019632533611881366
0.3320094390941135
1.3152320916805154
-0.5398038985775272
3.7798384144965924
0.36797187072543575
6.183015818727054
1.0784782720565904
-1.064874495583498
1.2759775419695678
0.5065856754614081
0.955358

In [17]:
def HT( v, k ):
    t = np.zeros_like( v )
    if k < 1:
        return t
    else:
        ind = np.argsort( abs( v ) )[ -k: ]
        t[ ind ] = v[ ind ]
        return t


In [18]:
thetha=HT(optimized_theta,256)

In [21]:
for i in range(0, len(optimized_theta)):    
    print(thetha[i]),

2028.077292645158
0.0
0.0
0.0
0.0
3.8972597433413445
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.7747803478417445
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.517819620367487
0.0
0.0
0.0
0.0
3.113644830204942
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.7798384144965924
0.0
6.183015818727054
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.008134503224346
4.74236084795359
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.8299473359760854
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.2067517761855653
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.9755736745404824
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.838200341767642
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.305944618429192
3.0460262849141295
0.0
5.539039209793952
0.0
0.0
0.0
0.0
0.0
3.6182092373597947
0.0
0.0
0.0
0.0
0.0
0.0
8.499645400626573
13.454883592089407
0.0
3.3064338946386886
0.0
0.0
0.0
0.0
0.0
8.416866607370462
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0